package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Cspciuda generated by hbm2java
 */
public class Cspciuda implements java.io.Serializable, AbstractBO<CspciudaId> {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private CspciudaId id;
    private String ciunciuaf;

    public Cspciuda() {
    }

    public Cspciuda(CspciudaId id, String ciunciuaf) {
        this.id = id;
        this.ciunciuaf = ciunciuaf;
    }

    public CspciudaId getId() {
        return this.id;
    }

    public void setId(CspciudaId id) {
        this.id = id;
    }

    public String getCiunciuaf() {
        return this.ciunciuaf;
    }

    public void setCiunciuaf(String ciunciuaf) {
        this.ciunciuaf = ciunciuaf;
    }

    @Override
    public CspciudaId getPrimaryKey() {
        return id;
    }

    @Override
    public void cleanObject() {

    }

}
