package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Csptpais generated by hbm2java
 */
public class Csptpais implements java.io.Serializable,AbstractBO<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String paicpaiak;
	private String paidpaiaf;

	public Csptpais() {
	}

	public Csptpais(String paicpaiak, String paidpaiaf) {
		this.paicpaiak = paicpaiak;
		this.paidpaiaf = paidpaiaf;
	}

	public String getPaicpaiak() {
		return this.paicpaiak;
	}

	public void setPaicpaiak(String paicpaiak) {
		this.paicpaiak = paicpaiak;
	}

	public String getPaidpaiaf() {
		return this.paidpaiaf;
	}

	public void setPaidpaiaf(String paidpaiaf) {
		this.paidpaiaf = paidpaiaf;
	}

	@Override
	public String getPrimaryKey() {
		return paicpaiak;
	}

	@Override
	public void cleanObject() {
		
	}

}
