package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Csptieve generated by hbm2java
 */
public class Csptieve implements java.io.Serializable,AbstractBO<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tevctevnk;
	private String tevntevaf;
	private String tevdtesaf;

	public Csptieve() {
	}

	public Csptieve(String tevntevaf, String tevdtesaf) {
		this.tevntevaf = tevntevaf;
		this.tevdtesaf = tevdtesaf;
	}

	public Integer getTevctevnk() {
		return this.tevctevnk;
	}

	public void setTevctevnk(Integer tevctevnk) {
		this.tevctevnk = tevctevnk;
	}

	public String getTevntevaf() {
		return this.tevntevaf;
	}

	public void setTevntevaf(String tevntevaf) {
		this.tevntevaf = tevntevaf;
	}

	public String getTevdtesaf() {
		return this.tevdtesaf;
	}

	public void setTevdtesaf(String tevdtesaf) {
		this.tevdtesaf = tevdtesaf;
	}

	@Override
	public Integer getPrimaryKey() {
		return tevctevnk;
	}

	@Override
	public void cleanObject() {
		
	}

}
