package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Esdimaes generated by hbm2java
 */
public class Esdimaes implements java.io.Serializable, AbstractBO<EsdimaesId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EsdimaesId id;
	private String iesrimaaf;

	public Esdimaes() {
	}

	public Esdimaes(EsdimaesId id, String iesrimaaf) {
		this.id = id;
		this.iesrimaaf = iesrimaaf;
	}

	public EsdimaesId getId() {
		return this.id;
	}

	public void setId(EsdimaesId id) {
		this.id = id;
	}

	public String getIesrimaaf() {
		return this.iesrimaaf;
	}

	public void setIesrimaaf(String iesrimaaf) {
		this.iesrimaaf = iesrimaaf;
	}

	@Override
	public EsdimaesId getPrimaryKey() {
		return id;
	}

	@Override
	public void cleanObject() {

	}

}
