package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Esdimope generated by hbm2java
 */
public class Esdimope implements java.io.Serializable,AbstractBO<EsdimopeId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EsdimopeId id;
	private String ioerimaaf;

	public Esdimope() {
	}

	public Esdimope(EsdimopeId id, String ioerimaaf) {
		this.id = id;
		this.ioerimaaf = ioerimaaf;
	}

	public EsdimopeId getId() {
		return this.id;
	}

	public void setId(EsdimopeId id) {
		this.id = id;
	}

	public String getIoerimaaf() {
		return this.ioerimaaf;
	}

	public void setIoerimaaf(String ioerimaaf) {
		this.ioerimaaf = ioerimaaf;
	}

	@Override
	public EsdimopeId getPrimaryKey() {
		return id;
	}

	@Override
	public void cleanObject() {
		
	}

}
