package com.vegadvisor.client.bo;

import java.util.List;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Esdopies generated by hbm2java
 */
public class Esdopies implements java.io.Serializable, AbstractBO<EsdopiesId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EsdopiesId id;
	private String usucusuak;
	private int oesnestnf;
	private String oesdetoaf;
	// Nombre del usuario que hace la opinion
	private String userName;
	// Lista de imagenes de la opinion
	private List<Esdimope> images;

	public Esdopies() {
	}

	public Esdopies(EsdopiesId id, String usucusuak, int oesnestnf,
			String oesdetoaf) {
		this.id = id;
		this.usucusuak = usucusuak;
		this.oesnestnf = oesnestnf;
		this.oesdetoaf = oesdetoaf;
	}

	public EsdopiesId getId() {
		return this.id;
	}

	public void setId(EsdopiesId id) {
		this.id = id;
	}

	public String getUsucusuak() {
		return this.usucusuak;
	}

	public void setUsucusuak(String usucusuak) {
		this.usucusuak = usucusuak;
	}

	public int getOesnestnf() {
		return this.oesnestnf;
	}

	public void setOesnestnf(int oesnestnf) {
		this.oesnestnf = oesnestnf;
	}

	public String getOesdetoaf() {
		return this.oesdetoaf;
	}

	public void setOesdetoaf(String oesdetoaf) {
		this.oesdetoaf = oesdetoaf;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName
	 *            the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Override
	public EsdopiesId getPrimaryKey() {
		return id;
	}

	/**
	 * @return the images
	 */
	public List<Esdimope> getImages() {
		return images;
	}

	/**
	 * @param images
	 *            the images to set
	 */
	public void setImages(List<Esdimope> images) {
		this.images = images;
	}

	@Override
	public void cleanObject() {

	}

}
