package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Evdevvus generated by hbm2java
 */
public class Evdevvus implements java.io.Serializable, AbstractBO<EvdevvusId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EvdevvusId id;
	private String evuindpvf;

	public Evdevvus() {
	}

	public Evdevvus(EvdevvusId id, String evuindpvf) {
		this.id = id;
		this.evuindpvf = evuindpvf;
	}

	public EvdevvusId getId() {
		return this.id;
	}

	public void setId(EvdevvusId id) {
		this.id = id;
	}

	public String getEvuindpvf() {
		return this.evuindpvf;
	}

	public void setEvuindpvf(String evuindpvf) {
		this.evuindpvf = evuindpvf;
	}

	@Override
	public EvdevvusId getPrimaryKey() {

		return id;
	}

	@Override
	public void cleanObject() {

		
	}

}
