package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Evdimaev generated by hbm2java
 */
public class Evdimaev implements java.io.Serializable,AbstractBO<EvdimaevId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EvdimaevId id;
	private String imerimaaf;

	public Evdimaev() {
	}

	public Evdimaev(EvdimaevId id, String imerimaaf) {
		this.id = id;
		this.imerimaaf = imerimaaf;
	}

	public EvdimaevId getId() {
		return this.id;
	}

	public void setId(EvdimaevId id) {
		this.id = id;
	}

	public String getImerimaaf() {
		return this.imerimaaf;
	}

	public void setImerimaaf(String imerimaaf) {
		this.imerimaaf = imerimaaf;
	}

	@Override
	public EvdimaevId getPrimaryKey() {

		return id;
	}

	@Override
	public void cleanObject() {
		
	}

}
