package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UsdcheusId generated by hbm2java
 */
public class UsdcheusId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String usucusuak;
	private int estcestnk;
	private Date chufregfk;
	private int chucchunk;

	public UsdcheusId() {
	}

	public UsdcheusId(String usucusuak, int estcestnk, Date chufregfk,
			int chucchunk) {
		this.usucusuak = usucusuak;
		this.estcestnk = estcestnk;
		this.chufregfk = chufregfk;
		this.chucchunk = chucchunk;
	}

	public String getUsucusuak() {
		return this.usucusuak;
	}

	public void setUsucusuak(String usucusuak) {
		this.usucusuak = usucusuak;
	}

	public int getEstcestnk() {
		return this.estcestnk;
	}

	public void setEstcestnk(int estcestnk) {
		this.estcestnk = estcestnk;
	}

	public Date getChufregfk() {
		return this.chufregfk;
	}

	public void setChufregfk(Date chufregfk) {
		this.chufregfk = chufregfk;
	}

	public int getChucchunk() {
		return this.chucchunk;
	}

	public void setChucchunk(int chucchunk) {
		this.chucchunk = chucchunk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsdcheusId))
			return false;
		UsdcheusId castOther = (UsdcheusId) other;

		return ((this.getUsucusuak() == castOther.getUsucusuak()) || (this
				.getUsucusuak() != null && castOther.getUsucusuak() != null && this
				.getUsucusuak().equals(castOther.getUsucusuak())))
				&& (this.getEstcestnk() == castOther.getEstcestnk())
				&& ((this.getChufregfk() == castOther.getChufregfk()) || (this
						.getChufregfk() != null
						&& castOther.getChufregfk() != null && this
						.getChufregfk().equals(castOther.getChufregfk())))
				&& (this.getChucchunk() == castOther.getChucchunk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsucusuak() == null ? 0 : this.getUsucusuak().hashCode());
		result = 37 * result + this.getEstcestnk();
		result = 37 * result
				+ (getChufregfk() == null ? 0 : this.getChufregfk().hashCode());
		result = 37 * result + this.getChucchunk();
		return result;
	}

}
