package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usdcheus generated by hbm2java
 */
public class Usdcheus implements java.io.Serializable,AbstractBO<UsdcheusId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsdcheusId id;
	private Date chuhoratf;

	public Usdcheus() {
	}

	public Usdcheus(UsdcheusId id, Date chuhoratf) {
		this.id = id;
		this.chuhoratf = chuhoratf;
	}

	public UsdcheusId getId() {
		return this.id;
	}

	public void setId(UsdcheusId id) {
		this.id = id;
	}

	public Date getChuhoratf() {
		return this.chuhoratf;
	}

	public void setChuhoratf(Date chuhoratf) {
		this.chuhoratf = chuhoratf;
	}

	@Override
	public UsdcheusId getPrimaryKey() {
		return id;
	}

	@Override
	public void cleanObject() {
		
	}

}
