package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usdusubl generated by hbm2java
 */
public class Usdusubl implements java.io.Serializable,AbstractBO<UsdusublId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsdusublId id;
	private Date usufbloff;
	private Date usuhblotf;
	private String usutblovf;

	public Usdusubl() {
	}

	public Usdusubl(UsdusublId id, Date usufbloff, Date usuhblotf,
			String usutblovf) {
		this.id = id;
		this.usufbloff = usufbloff;
		this.usuhblotf = usuhblotf;
		this.usutblovf = usutblovf;
	}

	public UsdusublId getId() {
		return this.id;
	}

	public void setId(UsdusublId id) {
		this.id = id;
	}

	public Date getUsufbloff() {
		return this.usufbloff;
	}

	public void setUsufbloff(Date usufbloff) {
		this.usufbloff = usufbloff;
	}

	public Date getUsuhblotf() {
		return this.usuhblotf;
	}

	public void setUsuhblotf(Date usuhblotf) {
		this.usuhblotf = usuhblotf;
	}

	public String getUsutblovf() {
		return this.usutblovf;
	}

	public void setUsutblovf(String usutblovf) {
		this.usutblovf = usutblovf;
	}

	@Override
	public UsdusublId getPrimaryKey() {
		return id;
	}

	@Override
	public void cleanObject() {
		
	}

}
