package com.vegadvisor.client.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usmusuar generated by hbm2java
 */
public class Usmusuar implements java.io.Serializable, AbstractBO<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usucusuak;
	private String usuemaiaf;
	private String usunusuaf;
	private String usuapelaf;
	private Date usufnacff;
	private String usugenpvf;
	private String usufotoaf;
	private String usuvegasf;
	private String usuaficaf;
	private String paicpaiak;
	private String ciucciuak;
	private String usuiactsf;
	private String usupassaf;

	public Usmusuar() {
	}

	public Usmusuar(String usucusuak, String usuemaiaf, String usunusuaf,
			String usuapelaf, Date usufnacff, String usugenpvf,
			String usufotoaf, String usuvegasf, String usuaficaf,
			String paicpaiak, String ciucciuak, String usuiactsf,
			String usupassaf) {
		this.usucusuak = usucusuak;
		this.usuemaiaf = usuemaiaf;
		this.usunusuaf = usunusuaf;
		this.usuapelaf = usuapelaf;
		this.usufnacff = usufnacff;
		this.usugenpvf = usugenpvf;
		this.usufotoaf = usufotoaf;
		this.usuvegasf = usuvegasf;
		this.usuaficaf = usuaficaf;
		this.paicpaiak = paicpaiak;
		this.ciucciuak = ciucciuak;
		this.usuiactsf = usuiactsf;
		this.setUsupassaf(usupassaf);
	}

	public String getUsucusuak() {
		return this.usucusuak;
	}

	public void setUsucusuak(String usucusuak) {
		this.usucusuak = usucusuak;
	}

	public String getUsuemaiaf() {
		return this.usuemaiaf;
	}

	public void setUsuemaiaf(String usuemaiaf) {
		this.usuemaiaf = usuemaiaf;
	}

	public String getUsunusuaf() {
		return this.usunusuaf;
	}

	public void setUsunusuaf(String usunusuaf) {
		this.usunusuaf = usunusuaf;
	}

	public String getUsuapelaf() {
		return this.usuapelaf;
	}

	public void setUsuapelaf(String usuapelaf) {
		this.usuapelaf = usuapelaf;
	}

	public Date getUsufnacff() {
		return this.usufnacff;
	}

	public void setUsufnacff(Date usufnacff) {
		this.usufnacff = usufnacff;
	}

	public String getUsugenpvf() {
		return this.usugenpvf;
	}

	public void setUsugenpvf(String usugenpvf) {
		this.usugenpvf = usugenpvf;
	}

	public String getUsufotoaf() {
		return this.usufotoaf;
	}

	public void setUsufotoaf(String usufotoaf) {
		this.usufotoaf = usufotoaf;
	}

	public String getUsuvegasf() {
		return this.usuvegasf;
	}

	public void setUsuvegasf(String usuvegasf) {
		this.usuvegasf = usuvegasf;
	}

	public String getUsuaficaf() {
		return this.usuaficaf;
	}

	public void setUsuaficaf(String usuaficaf) {
		this.usuaficaf = usuaficaf;
	}

	public String getPaicpaiak() {
		return this.paicpaiak;
	}

	public void setPaicpaiak(String paicpaiak) {
		this.paicpaiak = paicpaiak;
	}

	public String getCiucciuak() {
		return this.ciucciuak;
	}

	public void setCiucciuak(String ciucciuak) {
		this.ciucciuak = ciucciuak;
	}

	public String getUsuiactsf() {
		return this.usuiactsf;
	}

	public void setUsuiactsf(String usuiactsf) {
		this.usuiactsf = usuiactsf;
	}

	/**
	 * @return the usupassaf
	 */
	public String getUsupassaf() {
		return usupassaf;
	}

	/**
	 * @param usupassaf
	 *            the usupassaf to set
	 */
	public void setUsupassaf(String usupassaf) {
		this.usupassaf = usupassaf;
	}

	@Override
	public String getPrimaryKey() {
		return usucusuak;
	}

	@Override
	public void cleanObject() {

	}

}
